### ISSUE TITLE
Questions about sowfa coupling Openfast

### ISSUE THREAD

**Issue by HYFOAM** [pablo-benito/SOWFA-installation#4] opened 2020-08-25 07:28 UTC
Dear pablo-benito:
   Hello, when I installed Openfast, OpenFOAM and SOWFA in your way, I tried to run the 5MW calculation in SOWFA and an error occurred. The error is as follows, do you have a good solution? thank you!

Running ElastoDyn.
Running AeroDyn.
[0] #0 Foam::error::printStack(Foam::Ostream&) at ??:?
[0] #1 Foam::sigSegv::sigHandler(int) at ??:?
[0] #2 ? in "/lib/x86_64-linux-gnu/libpthread.so.0"
[0] #3 FAST_OpFM_Init at ??:?
[0] #4 fast::OpenFAST::init() at ??:?
[0] #5 Foam::turbineModels::horizontalAxisWindTurbinesALMOpenFAST::initialize() at ??:?
[0] #6 Foam::turbineModels::horizontalAxisWindTurbinesALMOpenFAST::horizontalAxisWindTurbinesALMOpenFAST(Foam::GeometricField<Foam::Vector, Foam::fvPatchField, Foam::volMesh> const&) at ??:?
[0] #7 ? in "/home/antonio/OpenFOAM/OpenFOAM-2.4.0/platforms/linux64GccDPOpt/bin/pisoFoamTurbine.ALMAdvancedOpenFAST"
[0] #8 __libc_start_main in "/lib/x86_64-linux-gnu/libc.so.6"
[0] #9 ? in "/home/antonio/OpenFOAM/OpenFOAM-2.4.0/platforms/linux64GccDPOpt/bin/pisoFoamTurbine.ALMAdvancedOpenFAST"
[antonio-X556URK:17711] *** Process received signal ***
[antonio-X556URK:17711] Signal: Segmentation fault (11)
[antonio-X556URK:17711] Signal code: (-6)
[antonio-X556URK:17711] Failing at address: 0x3e80000452f
[antonio-X556URK:17711] [ 0] /lib/x86_64-linux-gnu/libpthread.so.0(+0x13f40)[0x7fd7c25bff40]
[antonio-X556URK:17711] [ 1] /lib/x86_64-linux-gnu/libpthread.so.0(raise+0xc7)[0x7fd7c25bfdd7]
[antonio-X556URK:17711] [ 2] /lib/x86_64-linux-gnu/libpthread.so.0(+0x13f40)[0x7fd7c25bff40]
[antonio-X556URK:17711] [ 3] /home/antonio/SOWFA/lib/linux64GccDPOpt/libSOWFATurbineModelsOpenFAST.so(FAST_OpFM_Init+0x5a5)[0x7fd7c59d8d35]
[antonio-X556URK:17711] [ 4] /home/antonio/SOWFA/lib/linux64GccDPOpt/libSOWFATurbineModelsOpenFAST.so(_ZN4fast8OpenFAST4initEv+0x5a3)[0x7fd7c59d4a63]
[antonio-X556URK:17711] [ 5] /home/antonio/SOWFA/lib/linux64GccDPOpt/libSOWFATurbineModelsOpenFAST.so(_ZN4Foam13turbineModels37horizontalAxisWindTurbinesALMOpenFAST10initializeEv+0x43)[0x7fd7c5997773]
[antonio-X556URK:17711] [ 6] /home/antonio/SOWFA/lib/linux64GccDPOpt/libSOWFATurbineModelsOpenFAST.so(_ZN4Foam13turbineModels37horizontalAxisWindTurbinesALMOpenFASTC2ERKNS_14GeometricFieldINS_6VectorIdEENS_12fvPatchFieldENS_7volMeshEEE+0x1ea7)[0x7fd7c5999967]
[antonio-X556URK:17711] [ 7] pisoFoamTurbine.ALMAdvancedOpenFAST(+0x42b28)[0x5598a4356b28]
[antonio-X556URK:17711] [ 8] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xeb)[0x7fd7c23e7b6b]
[antonio-X556URK:17711] [ 9] pisoFoamTurbine.ALMAdvancedOpenFAST(+0x4887a)[0x5598a435c87a]
[antonio-X556URK:17711] *** End of error message ***

Primary job terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.

mpirun noticed that process rank 0 with PID 0 on node antonio-X556URK exited on signal 11 (Segmentation fault).

**Comment by pablo-benito** [comment] 2021-05-13 09:53
Sorry I saw this now... 

Anyway, the error is too generic (It's a segfault) to say something. Without more info it's complicated to help. 

But, again, this issue is not related with the content of this repo: A guide to compile & install SOWFA. 
For issues related with running SOWFA, you should ask in the original source, the NREL/SOWFA repository

Well, the issue is too old now, so I'm going to close this issue.

**Closed by pablo-benito** 2021-05-13 09:53 UTC

**Comment by HYFOAM** [comment] 2021-05-13 09:58
Thank you for your answer! I have solved the problem. @pablo-benito

**Comment by pablo-benito** [comment] 2021-05-13 10:01
So sorry for the delay... It's been a though year, you know..
